name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1 # v1.0.0
        id: app-token
        with:
          app-id: ${{ vars.PUBLISH_APP_ID }}
          private-key: ${{ secrets.PUBLISH_APP_PRIVATE_KEY }}
          owner: Warashi
          repositories: milky-way
      - name: Checkout milky-way
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: "Warashi/milky-way"
          path: milky-way
          persist-credentials: false
      - name: Checkout warashi.dev
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: warashi-dev
          persist-credentials: false
      - name: Copy contents from warashi.dev to milky-way
        run: |
          mkdir -p milky-way/content milky-way/public milky-way/data
          cp -r warashi-dev/data/* milky-way/data/ || true
          cp -r warashi-dev/content/* milky-way/content/ || true
          cp -r warashi-dev/static/* milky-way/public/ || true
      - name: Install dependencies
        run: |
          cd milky-way
          npm ci
      - name: Build
        run: |
          cd milky-way
          npm run build
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: milky-way/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
